# Generated by Django 2.1.7 on 2019-06-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='project_img_alt',
            field=models.CharField(default='Image Alt Text', max_length=250),
        ),
    ]
