# Generated by Django 2.1.7 on 2019-07-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectspage_project_img_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='project_canonical',
            field=models.URLField(default='Canonical URL'),
        ),
    ]
