# Generated by Django 2.1.7 on 2019-07-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('projects', '0006_datatest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatest',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='DataTest',
        ),
    ]
