# Generated by Django 2.1.7 on 2019-08-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190721_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsprojectspage',
            old_name='ds_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='projectspage',
            old_name='project_image',
            new_name='image',
        ),
    ]
