# Generated by Django 2.1.7 on 2019-08-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190811_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsprojectspage',
            old_name='image',
            new_name='ds_image',
        ),
        migrations.RenameField(
            model_name='projectspage',
            old_name='image',
            new_name='project_image',
        ),
    ]
