# Generated by Django 2.1.7 on 2019-08-11 19:23

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190811_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsprojectspage',
            name='problem_statement',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
