# Generated by Django 2.1.7 on 2019-08-13 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190811_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataWine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=250)),
                ('points', models.IntegerField(max_length=250)),
                ('price', models.IntegerField(max_length=250)),
                ('province', models.CharField(max_length=250)),
                ('region_1', models.CharField(max_length=250)),
                ('region_2', models.CharField(max_length=250)),
                ('taster_name', models.CharField(max_length=250)),
                ('taster_twitter_handle', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('variety', models.CharField(max_length=250)),
                ('winery', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='dsprojectspage',
            name='ds_dataset',
        ),
    ]
