# Generated by Django 2.1.7 on 2019-08-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190813_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datawine',
            name='taster_name',
        ),
        migrations.RemoveField(
            model_name='datawine',
            name='taster_twitter_handle',
        ),
        migrations.RemoveField(
            model_name='datawine',
            name='title',
        ),
        migrations.AlterField(
            model_name='datawine',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datawine',
            name='price',
            field=models.IntegerField(),
        ),
    ]
