# Generated by Django 2.1.7 on 2019-08-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20190813_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataWine',
        ),
    ]
