# Generated by Django 2.1.7 on 2019-08-16 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_delete_datawine'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataWine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=250)),
                ('points', models.IntegerField()),
                ('price', models.IntegerField()),
                ('province', models.CharField(max_length=250)),
                ('region_1', models.CharField(max_length=250)),
                ('region_2', models.CharField(max_length=250)),
                ('variety', models.CharField(max_length=250)),
                ('winery', models.CharField(max_length=250)),
            ],
        ),
    ]
