# Generated by Django 2.1.7 on 2019-07-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='canonical',
            field=models.URLField(default='Canonical URL'),
        ),
    ]
