# Generated by Django 2.1.7 on 2019-05-27 17:21

from django.db import migrations, models
import django.db.models.deletion
import wagtailschemaorg.registry


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvRo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('twitter_handle', models.CharField(max_length=15)),
                ('facebook_url', models.URLField()),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtailschemaorg.registry.SiteThingLD, models.Model),
        ),
    ]
