# Generated by Django 2.1.7 on 2019-06-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190527_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteschema',
            name='site',
        ),
        migrations.DeleteModel(
            name='SiteSchema',
        ),
    ]
