# Generated by Django 2.1.7 on 2019-07-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='canonical',
            field=models.URLField(default='Canonical URL'),
        ),
    ]
