# Generated by Django 2.1.7 on 2019-07-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_index', '0002_auto_20190514_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectindexpage',
            name='canonical',
            field=models.URLField(default='Canonical URL'),
        ),
    ]
